### ISSUE TITLE
Are non-unique census block values correct?

### ISSUE THREAD

**Issue by mattyschell** [mattyschell/mobilelatlong2cloud#4]
In the legacy application the returned values for census blocks are 4 digit block codes.  Because census block codes are only unique within census tracts the 4-digit returned value for census blocks (alone) are not useful.  

Here's a small selection of layer_name=CENSUSBLOCK feature_value = 2002.

![image](https://github.com/user-attachments/assets/fcd2acad-4279-4893-85e6-e76e59dc0147)

For now we will assume that the consumers of this service want these non-unique values and always combine census blocks with other returned values like borough and census tract. The other possibility is that this is a mistake in the data and whoever last loaded the legacy application simply  selected the wrong column to use as the feature_value source.

@mlipper please review and let me know if you think otherwise.

**Comment by mlipper** [comment]
Is there a proper spatial (e.g., "inner join" in non-spatial context) relationship between census block, tract, borough values returned by a successful point-in-polygon query? If so, then, for now at least, I think your assumption that the existing discrete set of data attributes is correct.

**Comment by mattyschell** [comment]
Yes, blocks nest within tracts and tracts nest within boroughs.

Great, thank you @mlipper closing this!
