### ISSUE TITLE
Determine correct fire company values

### ISSUE THREAD

**Issue by mattyschell** [mattyschell/mobilelatlong2cloud#8]
The FDNY identifies fire companies using an initial letter value:

- (L)adder
- (E)ngine 
- Fire S(Q)uad

Followed by a space and 1 to 3 digits.  For example Engine 1 of lower Manhattan, Ladder 1 of midtown, and Squad 1 of Brooklyn are, respectively:

- E 1
- L 1
- Q  1

The legacy application ignores the initial letter and left pads with zeros.  The three records above are 

- 001
- 001
- 001

This is almost certainly wrong.  But @mlipper and the business should probably take a quick look and confirm that we should continue with the style of wrongness that we know and love.

**Comment by mlipper** [comment]
Geoclient returns several discrete elements from Geosupport:

```json
"fireBattalion": "11",
"fireCompanyNumber": "076",
"fireCompanyType": "E",
"fireDivision": "03",
...
```
However, we are probably just rearranging deck chairs on the Titanic right now. ***sigh***... I see 2 options:

1. Preserve the sillyness
2. Ask the client if they want this change. My guess is that the answer depends only on the type and width/precision of RDBMS field used to store this value: if the correct data will fit, then correct value. If no, then option 1.

I'll get back to you unless you have a preference.

**Comment by mattyschell** [comment]
The consumers of the service no longer require fire company. Closing.
