### ISSUE TITLE
Determine Correct HousingDistrict Values

### ISSUE THREAD

**Issue by mattyschell** [mattyschell/mobilelatlong2cloud#9]
In the legacy  application the HOUSINGDISTRICT layer has feature_values 1 through 9 and "SIHU."  

SIHU is easy enough to decode, these are on Staten Island.  The others not so much.  The numbers are spatially near one another.  These numbers are not currently published at NYC Open Data.  Here are 32 records with feature value 5 highlighted yellow, as an example.

![image](https://github.com/user-attachments/assets/982e3eb2-2908-4573-8ffe-c7179438318a)

"NYCHA Public Housing Developments" on NYC Open Data are now uniquely identified by a TDS_NUM.  The record for a TDS_NUM is unique but may be a multipolygon.  Highlighted in yellow here is Queensbridge South, tds_num = 5.

![image](https://github.com/user-attachments/assets/9a6d7367-e221-4572-b929-101c9186e56f)

For now we will assume that tds_num is the way to go, we love a good cover page on our tds_num reports.  @mlipper and the users should confirm.

**Comment by mlipper** [comment]
I have no earthly idea. Perhaps I can talk to you tomorrow (8/13) and, if appropriate, I can reach out to Dr. Doug who used to know way too much about this subject.

**Comment by mattyschell** [comment]
Link to Housing Authority Developments on NYC Open Data: https://data.cityofnewyork.us/Housing-Development/NYCHA-Public-Housing-Developments-Map/npwq-dpkb

**Comment by mattyschell** [comment]
Here's a longitude,latitude for Bayview Houses

http://xxxxx/api/latlong/v1/location.xml?x=-73.88586176694784&y=40.63329647792608&key=xxx

**Comment by mattyschell** [comment]
The consumers of the service no longer require housing district. Closing.
